global:
  enabledModules: ["vertical-pod-autoscaler-crd", "prometheus", "priority-class"]
  modulesImages:
    registry: registry.deckhouse.io/deckhouse/fe
    registryDockercfg: Y2ZnCg==
    tags:
      networkGateway: {}
      common: {}
  discovery:
    clusterControlPlaneIsHighlyAvailable: true
    d8SpecificNodeCountByRole:
      system: 1
    kubernetesVersion: 1.15.5
  modules:
    placement:
      __ConstantChoices__:
        - {}
        - customTolerationKeys: ["key-key"]
