// Code generated by "go generate ./tools/register.go". DO NOT EDIT!
package main

import (
	_ "github.com/deckhouse/deckhouse/go_lib/deckhouse-config/conversion"

	_ "github.com/deckhouse/deckhouse/modules/101-cert-manager/config-values-conversion"
)
