global:
  clusterConfiguration:
    apiVersion: deckhouse.io/v1
    kind: ClusterConfiguration
    podSubnetNodeCIDRPrefix: "24"
    podSubnetCIDR: 10.244.0.0/16
    serviceSubnetCIDR: 192.168.0.0/16
    kubernetesVersion: "1.19"
    clusterDomain: test
    clusterType: "Cloud"
    cloud:
      prefix: test
      provider: Azure
  enabledModules:
    __ConstantChoices__:
      - ["vertical-pod-autoscaler-crd"]
      - ["priority-class"]
  modulesImages:
    registry: registry.deckhouse.io/deckhouse/fe
    registryDockercfg: Y2ZnCg==
    tags:
      cloudProviderAzure: {}
      common: {}
  discovery:
    d8SpecificNodeCountByRole:
      worker: 1
      master:
        __ConstantChoices__: ["1", "3"]
    podSubnet: 10.0.1.0/16
    kubernetesVersion: 1.19.0
  modules:
    placement:
      __ConstantChoices__:
      - {}
      - customTolerationKeys:
          - "test-1"
          - "test-2/master"

cloudProviderAzure:
  internal:
    providerClusterConfiguration:
      provider:
        clientId: zzz
        clientSecret: zzz
        subscriptionId: zzz
        tenantId: zzz
        location: zzz
    providerDiscoveryData:
      resourceGroupName: zzz
      vnetName: zzz
      subnetName: zzz
      instances:
        urn: zzz
        diskType: zzz
    storageClasses:
    - name: aaa
      type: AAA
    - name: bbb
      type: BBB
    - name: ccc
      type: CCC
