{{/* Global values for validating webhook.  */}}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-deckhouse-custom-tolerations
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  customTolerationKeys: {{ .Values.global.modules.placement.customTolerationKeys | toJson | b64enc | quote }}
